# spring.application.name=project-board

debug: false
# dependencies actual ?? ?? ?? ?? ??
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.basic.project_board: debug
    org.springframework.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://192.168.0.48:3306/board
    username: user01
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: false

  # data.sql ??? ??
  sql.init.mode: always

---




